# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'maven'
    target-branch: 'develop'
    directory: '/'
    schedule:
      interval: 1h
    open-pull-requests-automatically: true
    allow-prerelease-updates: true
    version-updates:
      - type: 'semver-major'
        dependency-name: 'spring-boot-starter-parent'
        maven-central-group-id: 'org.springframework.boot'
        maven-central-artifact-id: 'spring-boot-starter-parent'
        maven-central-version: '>=3.0.8'
        monitor-release-tags: true
